engines:
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
    config: coffeelint.json
  csslint:
    enabled: true
  eslint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true

ratings:
  paths:
    - Gemfile.lock
    - "**.coffee"
    - "**.css"
    - "**.js"
    - "**.rb"
